### ISSUE TITLE
Export fails when product package doesn't have alias

### ISSUE THREAD

**Issue by MichalStehlikCz** [MichalStehlikCz/wikiloader#30]
Error message from log
2020-02-10 09:03:01,193 ERROR o.a.j.l.DirectJDKLog [http-nio-8080-exec-5] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.provys.common.exception.InternalException{nameNm="JAVA_INTERNAL_EXCEPTION", message="Cannot append link - boundary not exported EaProductPackageRef{not loaded} EaNamespaceElementRef{} EaElementRefBase{elementId=5924} EaObjectImpl{name='Basic Amortisation for All Rights - With Activation'alias='null', parent=EaPackageGroupRef{not loaded} EaPackageImpl{packageId=1334} EaObjectImpl{name='Finance'alias='finance', parent=EaPackageGroupRef{not loaded} EaPackageImpl{packageId=1116} EaObjectImpl{name='Rights'alias='rights', parent=EaPackageGroupRef{not loaded} EaPackageImpl{packageId=1112} EaObjectImpl{name='Product Packages'alias='product_packages', parent=EaPackageImpl{packageId=829} EaObjectImpl{name='Product Model'alias='eamodel', parent=null}}}}}", params={}, cause=null}] with root cause
com.provys.common.exception.InternalException: Cannot append link - boundary not exported EaProductPackageRef{not loaded} EaNamespaceElementRef{} EaElementRefBase{elementId=5924} EaObjectImpl{name='Basic Amortisation for All Rights - With Activation'alias='null', parent=EaPackageGroupRef{not loaded} EaPackageImpl{packageId=1334} EaObjectImpl{name='Finance'alias='finance', parent=EaPackageGroupRef{not loaded} EaPackageImpl{packageId=1116} EaObjectImpl{name='Rights'alias='rights', parent=EaPackageGroupRef{not loaded} EaPackageImpl{packageId=1112} EaObjectImpl{name='Product Packages'alias='product_packages', parent=EaPackageImpl{packageId=829} EaObjectImpl{name='Product Model'alias='eamodel', parent=null}}}}}
	at com.provys.wikiloader.earepository.impl.EaObjectRefBase.appendLink(EaObjectRefBase.java:167) ~[wikiloader-handler-1.0.3-SNAPSHOT.jar!/:?]
	at com.provys.wikiloader.earepository.impl.EaTechnicalPackageExporter.appendProductPackageLink(EaTechnicalPackageExporter.java:65) ~[wikiloader-handler-1.0.3-SNAPSHOT.jar!/:?]
	at com.provys.wikiloader.earepository.impl.EaTechnicalPackageExporter.appendContainedIn(EaTechnicalPackageExporter.java:73) ~[wikiloader-handler-1.0.3-SNAPSHOT.jar!/:?]
	at com.provys.wikiloader.earepository.impl.EaTechnicalPackageExporter.appendBody(EaTechnicalPackageExporter.java:114) ~[wikiloader-handler-1.0.3-SNAPSHOT.jar!/:?]
	at com.provys.wikiloader.earepository.impl.EaObjectRegularExporter.run(EaObjectRegularExporter.java:140) ~[wikiloader-handler-1.0.3-SNAPSHOT.jar!/:?]
	at com.provys.wikiloader.earepository.impl.EaObjectRegularBase.lambda$sync$0(EaObjectRegularBase.java:25) ~[wikiloader-handler-1.0.3-SNAPSHOT.jar!/:?]
	at java.util.Optional.ifPresentOrElse(Unknown Source) ~[?:?]
	at com.provys.wikiloader.earepository.impl.EaObjectRegularBase.sync(EaObjectRegularBase.java:25) ~[wikiloader-handler-1.0.3-SNAPSHOT.jar!/:?]
	at com.provys.wikiloader.earepository.impl.EaObjectRegularExporter.run(EaObjectRegularExporter.java:144) ~[wikiloader-handler-1.0.3-SNAPSHOT.jar!/:?]
	at com.provys.wikiloader.earepository.impl.EaObjectRegularBase.lambda$sync$0(EaObjectRegularBase.java:25) ~[wikiloader-handler-1.0.3-SNAPSHOT.jar!/:?]

**Comment by MichalStehlikCz** [comment]
There are in fact 3 problems
- exception handler doesn't handle conversion to text/plain - this is for provys-common library
- incorrect error message - it is not boundary, but regular object (copy&paste error)
- it should not fail, instead, it should export name of package without link
